### ISSUE TITLE
Create a message that we don't support IE 11

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#954]
From developer meeting today we decided to remove support for IE11. But first we will need to make sure that a message displays for IE 11 when running on that browser. It is not currently clear if the message says: "IE is not supported, go away", or more like "IE is not supported, continue and good luck, it will probably fail". 

Marking for developer meeting.

**Comment by mattpen** [comment]
Current website solution is below.  The `@supports (display: grid)` media query works on all modern browsers and does not work on IE, which is what allows this to work.

```html
<div id="ie11Blocker">
  <div class="modal">
    <p>
      <wicket:message key="ie11-blocking-message">
        The PhET website does not support Internet Explorer. We recommend using a modern web browser such as Chrome,
        Firefox, or Edge.
      </wicket:message>
    </p>
    <button id="ie11Blocker-close">
      <i class="fa fa-times"></i>
    </button>
  </div>

  <script>
    document.getElementById( 'ie11Blocker' ).addEventListener( 'click', function () {
      document.getElementById( 'ie11Blocker' ).style.display = 'none';
    } );
  </script>
</div>
```

```css
#ie11Blocker {
  display: flex;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 100vh;
  width: 100vw;
  background: rgba(0, 0, 0, .3);
  z-index: 10000;
  align-items: center;
}

#ie11Blocker .modal {
  position: relative;
  background: #efefef;
  border-radius: 10px;
  max-width: 410px;
  margin: auto;
  padding: 30px;
  font-size: 20px;
  font-weight: 100;
}

#ie11Blocker-close {
  position: absolute;
  top: 0;
  right: 0;
  background: transparent;
  border: none;
  padding: 5px 10px;
  cursor: pointer;
}

@supports (display: grid) {
  #ie11Blocker {
    display: none !important;
  }
}
```
